<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CEntidades\CEntidades.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="DataSets\Cuentas\General\DsCuentasActivas.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DsCuentasActivas.xsd</DependentUpon>
    </Compile>
    <Compile Update="DataSets\Cuentas\General\DsCuentasCanceladas.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DsCuentasCanceladas.xsd</DependentUpon>
    </Compile>
    <Compile Update="DataSets\Cuentas\General\DsCuentasGeneral.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DsCuentasGeneral.xsd</DependentUpon>
    </Compile>
    <Compile Update="DataSets\Cuentas\General\DsCuentasInactivas.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DsCuentasInactivas.xsd</DependentUpon>
    </Compile>
    <Compile Update="DataSets\Servicios\Depositos\DsDepositos.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DsDepositos.xsd</DependentUpon>
    </Compile>
    <Compile Update="DataSets\Servicios\Retiros\DsRetiros.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DsRetiros.xsd</DependentUpon>
    </Compile>
    <Compile Update="DataSets\Servicios\Transferencias\DsTransferencias.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DsTransferencias.xsd</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="DataSets\Cuentas\General\DsCuentasActivas.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>DsCuentasActivas.Designer.cs</LastGenOutput>
    </None>
    <None Update="DataSets\Cuentas\General\DsCuentasCanceladas.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>DsCuentasCanceladas.Designer.cs</LastGenOutput>
    </None>
    <None Update="DataSets\Cuentas\General\DsCuentasGeneral.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>DsCuentasGeneral.Designer.cs</LastGenOutput>
    </None>
    <None Update="DataSets\Cuentas\General\DsCuentasInactivas.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>DsCuentasInactivas.Designer.cs</LastGenOutput>
    </None>
    <None Update="DataSets\Servicios\Depositos\DsDepositos.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>DsDepositos.Designer.cs</LastGenOutput>
    </None>
    <None Update="DataSets\Servicios\Retiros\DsRetiros.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>DsRetiros.Designer.cs</LastGenOutput>
    </None>
    <None Update="DataSets\Servicios\Transferencias\DsTransferencias.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>DsTransferencias.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
